### ISSUE TITLE
Invalid Player Data Error

### ISSUE THREAD

**Issue by Bullseye55** [AzureDoom/MCDoom#19] opened 2021-11-14 02:31 UTC
When added to my modpack(of which I've updated the mods from previous versions in which MCDoom-Fabric worked with), upon connecting to a newly-generated singleplayer world, I am disconnected due to invalid player data with the accompanying screen. No crash log is generated.

I've attached the log that goes through pack load, world generation, and then the disconnect+shutdown. This pack works fine if MCDoom is not added, which is a major disappointment considering just how much your mod adds and how much I enjoy it. The Bumblezone also gives this error if added.

[latest.log](https://github.com/AzureDoom/MCDoom/files/7533079/latest.log)

**Comment by TelepathicGrunt** [comment] 2021-11-14 03:22
uh no one else reported that issue of Invalid Player Data with my mod The Bumblezone. This sounds more like some sort of issue with the pack. Are you using the latest version of cardinal components? Does the issue occur if you use only bumblezone or MCDoom without the rest of the modpack?

**Comment by Bullseye55** [comment] 2021-11-14 05:52
Yep, Cardinal Components is of the latest version.

Only using The Bumblezone or MCDoom works perfectly. Its a conflict, but I've been at a loss considering this invalid player data doesn't leave a good log cause.

**Comment by AzureDoom** [comment] 2021-11-14 13:34
Please try without Charm and see if it's caused again.

**Comment by Bullseye55** [comment] 2021-11-14 16:25
Just woke up, apologies for the response delay due to that and the fact I generated multiple worlds to rule out erroneous occurrence.

Removing Xaero's Worldmap caused Bumblezone to work, strangely.
As for MCDoom, disabling Xaero's Worldmap did not cause it to work, and disabling Charm also threw Invalid Player Data.

Bumblezone and MCDoom were tested separately, never added together.

**Comment by TelepathicGrunt** [comment] 2021-11-14 16:28
If you can send your modpack export/profile so we can autodownload all the mods, I can poke around myself later when I get time to see what’s up and what’s conflicting with what

**Comment by Bullseye55** [comment] 2021-11-14 16:36
Using MultiMC rather than the Curseforge launcher due to the myriad of Fabric tag errors and missings going on, so, I suppose a manual upload at 10 kb/sec will have to suffice. 
Owch. 667 MBs exported from MultiMC, so, three days. Not going to happen, hmmphic.

Is there another way I could do this more easily, TelepathicGrunt? 

Edit: Currently redoing the modlist via the Curseforge launcher. May take some time.

**Comment by Bullseye55** [comment] 2021-11-14 17:53
Here is the modpack, recompiled onto Curseforge's launcher to send.
[1.17.1 Main-1.zip](https://github.com/AzureDoom/MCDoom/files/7534301/1.17.1.Main-1.zip)

These mods have to be inserted manually due to missing Curseforge tags/versions or are on Modrinth/standalone:
https://www.curseforge.com/minecraft/mc-mods/trinket-of-undying-fabric
https://www.curseforge.com/minecraft/mc-mods/netherite-items
https://www.curseforge.com/minecraft/mc-mods/jjthunder-overhauled-world-generation
https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms-fabric
https://www.curseforge.com/minecraft/mc-mods/enchanted-tooltips
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric
https://www.curseforge.com/minecraft/mc-mods/terrarian-slimes
https://www.curseforge.com/minecraft/mc-mods/modern-glass-doors
https://www.curseforge.com/minecraft/mc-mods/status-crops
https://www.curseforge.com/minecraft/mc-mods/lemons-equivalence-fabric
https://www.curseforge.com/minecraft/mc-mods/fastdecay
https://www.curseforge.com/minecraft/mc-mods/controlling-for-fabric
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner
https://modrinth.com/mod/highlevelenchants
https://modrinth.com/mod/aoa
https://minecraftphysicsmod.com/download

**Comment by TelepathicGrunt** [comment] 2021-11-15 02:14
I tried to run the modpack with those mods but no luck. 
https://paste.ee/p/dP9LG
https://paste.ee/p/P8nn6

I keep crashing and cant figure out why the remapper is dying.

**Comment by Bullseye55** [comment] 2021-11-15 05:34
Curseforge is already proving to be an absolute headache due to version mismatches as I had suspected, blugg.

Its likely due to missing dependencies Curseforge isn't picking up due to version mismatching....and there may be more than these, so may want to reference the log above for a crossmatch of what Curseforge is leaving out, hmmphic:
https://www.curseforge.com/minecraft/mc-mods/libblockattributes
https://www.curseforge.com/minecraft/mc-mods/lib-network-stack
https://www.curseforge.com/minecraft/mc-mods/lib-multipart

**Comment by Bullseye55** [comment] 2021-11-15 05:36
[config.zip](https://github.com/AzureDoom/MCDoom/files/7536105/config.zip)

Also, here's the mod configs, so you can sync any compatibility changes I had to do through the pack's history. Can at least upload these....but wish I could upload the pack as well. Gack, hate making this such an inconvenience.

Late Edit: Heading to bed, but leaving the mods to upload overnight and will be posting them in the morning. That way, can sync both the configs above and the mod versions with you in the morning to better pinpoint this without the hassle. MultiMC will be able to distinguish the .disabled extensions on some of them(as its currently in this troubleshooting stage).

**Comment by Bullseye55** [comment] 2021-11-15 16:20
https://drive.google.com/file/d/1qd0iCcWmiFyd4VtFlWIxMVjPe-subu4r/view?usp=sharing

And here it is. Should make things easier than what Curseforge has going for it. Apologies for the triplepost.

**Comment by TelepathicGrunt** [comment] 2021-11-15 23:09
Thanks! Removing moreblocksmod-0.1.7.jar got the issue to stop for me while having all the other mods on. The fact that the issue seems to go away randomly based on which mod you remove seems to imply this is some sort of race condition. moreblocksmod's github doesn't show anything that would explain this so i don't they are the source of the issue. Probably not even Xaero, Bumblezone, and MCDoom might not be the cause. But I'm not sure how to fully go about this to figure out the true root cause

**Comment by TelepathicGrunt** [comment] 2021-11-15 23:32
I tried something as it seems the error was being swallowed. I did a print out and uh, looks like 
```
net.minecraft.class_148: Ticking memory connection
	at net.minecraft.class_3242.method_14357(class_3242.java:186) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.class_2658.<init>(class_2658.java:39) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:44) ~[fabric-networking-api-v1-1.0.14+5847535018-1eebb17708b29999.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:212) ~[fabric-networking-api-v1-1.0.14+5847535018-1eebb17708b29999.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.createPacket(RegistrySyncManager.java:74) ~[fabric-registry-sync-v0-0.7.13+5847535018-f73251e959997181.jar:?]
	at net.minecraft.class_3324.handler$cod003$onPlayerConnect(class_3324.java:8445) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:187) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:129) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3248.redirect$cnd000$handlePlayerJoin(class_3248.java:563) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-fabric-loader-0.12.5-1.17.1.jar:?]
	... 6 more
```

Your game has so much data that even XLPackets can't help. See if XLPackets has a config to increase the size of packets even more

**Comment by TelepathicGrunt** [comment] 2021-11-16 00:25
oh yeah btw,
![image](https://user-images.githubusercontent.com/40846040/141873526-efd66e6b-b60a-4e18-8776-db4943cc5c07.png)

The issue is that Fabric API's registry sync is unable to handle all of your mods on. If you make an issue report to Fabric API and link them my above message, they may try and fix their API to handle more data

**Comment by AzureDoom** [comment] 2021-11-16 00:26
Oh so it's just a literal two many mods at once thing? Wow lol

**Comment by TelepathicGrunt** [comment] 2021-11-16 01:01
@Bullseye55  Last thing before I go poof lol. I let XLPackets dev know about this and he just released an update to bump the hidden 1MB packet limit to 2GB so if you update that mod, you should be able to have more mods on now and not have the Fabric API registry sync die on you. https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric/files/3527187

**Comment by Bullseye55** [comment] 2021-11-16 07:12
Oh yes! This is news I could get used to. 

This "Invalid player data" error has been the bane of my Fabric modmaking, with a condition in that it has been -totally- inconsistent from pack beginning to end aside from 100% replicable cases like the one this thread is about.

Thank you! Glad I did post this after all.

**Comment by AzureDoom** [comment] 2021-11-16 08:43
@Bullseye55 assume the new XL Packets fixed it for you?

**Comment by Bullseye55** [comment] 2021-11-16 15:51
@AzureDoom, very much so. Even able to run some mods I had to neglect adding way before this. :)

**Comment by AzureDoom** [comment] 2021-11-16 15:57
Perfect, gonna be closing this then as it's resolved!

**Closed as completed by AzureDoom** 2021-11-16 15:57 UTC
